window.PHOTO_LIST = [
  'images/gallery/img0.png',
  'images/gallery/img1.png',
  'images/gallery/img2.png',
  'images/gallery/img3.png',
  'images/gallery/img4.png',
  'images/gallery/img5.png',
  'images/gallery/img6.png',
  'images/gallery/img7.png',
  'images/gallery/img8.png',
  'images/gallery/img9.png',
  'images/gallery/img10.png',
  'images/gallery/img11.png',
  'images/gallery/img12.png',
  'images/gallery/img13.png',
  'images/gallery/img14.png',
  'images/gallery/img15.png',
];
